### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by FelonEkonom** [membraneframework/membrane_h264_ffmpeg_plugin#99]
This issue is opend to check if auto-closing new issues works correctly

**Comment by membraneframeworkadmin** [comment]
Issues related to membraneframework/membrane_h264_ffmpeg_plugin are stored in [membrane_core](https://github.com/membraneframework/membrane_core), so we close this issue here and we encourage you to open it [there](https://github.com/membraneframework/membrane_core).
